//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperTech_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingLine
    {
        public int BookingID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> OptionID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceOption ServiceOption { get; set; }
    }
}
