//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperTech_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAuditTrail
    {
        public int AuditID { get; set; }
        public int ClientID { get; set; }
        public string CriticalData { get; set; }
        public string TablesAffected { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
